[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
setp = "setp"
exra = "exra"

[files]
extend-exclude = [
    ".gitignore",
    ".pre-commit-config.yaml",
    "*.json"
]
