[tool.poetry]
name = "mechanistic-model"
version = "0.1.0"
description = "CDC CFA Predict Scenarios model development"
authors = ["Your Name <you@example.com>"]
license = "Apache License, Version 2.0, January 2004"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
resp_ode = {path="src/", develop = true}
python = "^3.10"
cycler = ">=0.11.0"
diffrax = "0.5.0"
gitpython = ">=3.1.41"
jax = "<=0.4.26"
jaxlib = "<=0.4.26"
matplotlib = ">=3.7.2"
numpy = ">=1.25.2"
numpyro = ">=0.13.2"
pandas = ">=2.0.3"
seaborn = ">=0.13.2"
shiny = ">=0.6.0"
pytest = ">=7.4.0"
cfa-azure = {git = "https://github.com/CDCgov/cfa_azure.git"}
pip = "^24.0"
epiweeks = "^2.3.0"
pre-commit = "^3.7.1"
mypy = "^1.10.0"
requests = "^2.32.3"
docker = "^7.1.0"
bayeux-ml = "^0.1.14"
plotly = "^5.24.1"
shinywidgets = "^0.3.3"


[build-system]
build-backend = "poetry.core.masonry.api"
