[tool.poetry]
name = "dynode"
version = "0.2.0"
description = "CDC CFA Predict Scenarios model development"
authors = ["Your Name <you@example.com>"]
license = "Apache License, Version 2.0, January 2004"
readme = "README.md"
package-mode = true

[tool.poetry.dependencies]
python = "^3.12"
diffrax = "^0.6.0"
jax = "^0.4.28"
jaxlib = "^0.4.28"
numpy = ">=1.25.2"
numpyro = ">=0.13.2"
pandas = ">=2.0.3"
pytest = ">=7.4.0"
pip = "^24.0"
epiweeks = "^2.3.0"
pre-commit = "^3.7.1"
mypy = "^1.10.0"
requests = "^2.32.3"
docker = "^7.1.0"
bayeux-ml = "^0.1.14"
chex = "^0.1.87"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
