from __future__ import annotations

from math import prod
from types import SimpleNamespace
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, model_validator
from typing_extensions import Self

from dynode.typing import DynodeName

from .bin_spec import BinSpec
from .dimension_spec import AnyDimensionSpec

class _IntWithAttributes(int):
    """
    Integer index that can also expose named attributes.

    Example
    -------
    idx.age.adult

    where:
    - idx.age is the dimension index
    - idx.age.adult is the bin index within that dimension
    """

    def __new__(cls, value: int, **attributes: Any):
        obj = super().__new__(cls, value)

        for key, val in attributes.items():
            setattr(obj, key, val)

        return obj

    def __repr__(self) -> str:
        if self.__dict__:
            return f"{int(self)} {self.__dict__}"
        return str(int(self))

    def __str__(self) -> str:
        return str(int(self))

class CompartmentSpec(BaseModel):
    """
    Declarative specification for one ODE compartment.

    A compartment is one top-level component of the ODE state, such as:

        S
        E
        I
        R
        vaccinated
        hospitalized

    Each compartment may be stratified by zero or more dimensions.

    Examples
    --------
    Unstratified compartment:

        CompartmentSpec(name="S")

    Age-stratified compartment:

        CompartmentSpec(
            name="S",
            dimensions=(age_dimension,),
        )

    Age x immune-history stratified compartment:

        CompartmentSpec(
            name="S",
            dimensions=(age_dimension, immune_history_dimension),
        )

    This class should not:
    - know about parameters
    - know about strains
    - know about observed data
    - call NumPyro
    - build solver objects
    """

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        arbitrary_types_allowed=True,
    )

    name: DynodeName = Field(
        description="Compartment name. Must be unique within a SimulationSpec.",
    )

    dimensions: tuple[AnyDimensionSpec, ...] = Field(
        default_factory=tuple,
        description=(
            "Dimension definitions for this compartment. "
            "An empty tuple means the compartment is unstratified."
        ),
    )

    description: str | None = Field(
        default=None,
        description="Optional human-readable description of the compartment.",
    )

    metadata: dict[str, str] = Field(
        default_factory=dict,
        description="Optional metadata for documentation, UI display, or auditing.",
    )

    @model_validator(mode="after")
    def validate_compartment(self) -> Self:
        self._validate_unique_dimension_names()
        return self

    @property
    def dimension_names(self) -> list[str]:
        return [dimension.name for dimension in self.dimensions]

    @property
    def dimensions_to_idx(self) -> dict[str, int]:
        return {
            dimension.name: i
            for i, dimension in enumerate(self.dimensions)
        }

    @property
    def shape(self) -> tuple[int, ...]:
        """
        Shape of this compartment.

        Examples
        --------
        No dimensions:
            ()

        Age dimension with 5 bins:
            (5,)

        Age x immune history:
            (5, 8)
        """
        return tuple(len(dimension) for dimension in self.dimensions)

    @property
    def ndim(self) -> int:
        return len(self.shape)

    @property
    def size(self) -> int:
        """
        Total number of scalar state entries in this compartment.

        Unstratified compartments have shape () and size 1.
        """
        return prod(self.shape) if self.shape else 1

    @property
    def is_stratified(self) -> bool:
        return bool(self.dimensions)

    @property
    def is_scalar(self) -> bool:
        return not self.dimensions

    @property
    def idx(self) -> SimpleNamespace:
        """
        Enum-like index helper for dimension and bin lookup.

        Example
        -------
        compartment.idx.age
        compartment.idx.age.adult

        This is a convenience for model authoring. Runtime/JAX code should
        generally use plain integers, slices, arrays, or pytrees generated by
        the runtime compiler.
        """
        dims_namespace = SimpleNamespace()

        for dimension_idx, dimension in enumerate(self.dimensions):
            bin_attrs = self._bin_index_attrs(dimension)

            setattr(
                dims_namespace,
                dimension.name,
                _IntWithAttributes(
                    dimension_idx,
                    **bin_attrs,
                ),
            )

        return dims_namespace

    def get_dimension(self, name: str) -> DimensionSpec:
        for dimension in self.dimensions:
            if dimension.name == name:
                return dimension

        raise KeyError(
            f"Unknown dimension {name!r} in compartment {self.name!r}. "
            f"Known dimensions are: {self.dimension_names}."
        )

    def has_dimension(self, name: str) -> bool:
        return name in self.dimensions_to_idx

    def axis_of(self, dimension_name: str) -> int:
        """
        Return the axis index for a dimension.
        """
        try:
            return self.dimensions_to_idx[dimension_name]
        except KeyError as exc:
            raise KeyError(
                f"Unknown dimension {dimension_name!r} in compartment "
                f"{self.name!r}. Known dimensions are: {self.dimension_names}."
            ) from exc

    def bins_for_dimension(self, dimension_name: str) -> tuple[BinSpec, ...]:
        return tuple(self.get_dimension(dimension_name).bins)

    def dimension_size(self, dimension_name: str) -> int:
        return len(self.get_dimension(dimension_name))

    def flatten_bins(self) -> list[BinSpec]:
        """
        Flatten all bins in this compartment while preserving dimension order.
        """
        bins: list[BinSpec] = []

        for dimension in self.dimensions:
            bins.extend(dimension.bins)

        return bins

    def same_layout_as(
        self,
        other: CompartmentSpec,
        *,
        require_same_name: bool = False,
    ) -> bool:
        """
        Compare compartment layouts.

        Parameters
        ----------
        other:
            Another compartment spec.

        require_same_name:
            If True, names must also match. If False, only dimensions are
            compared.

        Returns
        -------
        bool
            Whether the compartments have compatible layouts.
        """
        if require_same_name and self.name != other.name:
            return False

        return self.dimensions == other.dimensions

    def _validate_unique_dimension_names(self) -> None:
        names = self.dimension_names
        duplicates = sorted({name for name in names if names.count(name) > 1})

        if duplicates:
            raise ValueError(
                f"Compartment {self.name!r} contains duplicate dimension "
                f"names: {duplicates}."
            )

    @staticmethod
    def _bin_index_attrs(dimension: DimensionSpec) -> dict[str, int]:
        """
        Build bin-name -> bin-index attributes for a dimension.

        If DimensionSpec already exposes an idx namespace, you could delegate to
        that instead. This implementation builds directly from dimension.bins.
        """
        attrs: dict[str, int] = {}

        for bin_idx, bin_ in enumerate(dimension.bins):
            bin_name = getattr(bin_, "name", None)

            if bin_name is None:
                raise ValueError(
                    f"Bin {bin_!r} in dimension {dimension.name!r} does not "
                    "expose a 'name' attribute."
                )

            attrs[bin_name] = bin_idx

        return attrs
