name: Generate Documentation

on:
  pull_request:
    branches:
      - main
      - development
      - doc-gen-test

jobs:
  generate-api-docs:
    name: API Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      - name: Install Dependencies
        run: |
          poetry install --no-root --with dev

      - name: Clean and Build HTML
        run: |
          ls
          cd docs
          poetry run make clean
          poetry run make html
