name: Run Pytest

on:
  push:


jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: poetry install
    - run: pytest
