name: Run pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install global dependencies
      run: |
        pip install poetry

    - name: Test
      run: |
        poetry install
        poetry run pytest -v
